import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/header/Header'
import Image from 'next/image'
import Query from './components/query/Query'
import Voyages from './components/voyages/Voyages'
import Support from './components/support/Support'
import moment from 'moment'
import { useEffect } from 'react'
import { filteredVoyages } from "./components/voyages/voyage"
import BookingPage from '@/pages/booking/booking'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
function getRandomDate(start: any, end: any) {
  const startTime = start.getTime();
  const endTime = end.getTime();
  const randomTime = startTime + Math.random() * (endTime - startTime);
  return new Date(randomTime);
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supportData = [
    {
      image: "/bus-ticket.png", description: "7/24 Müşteri Hizmetleri Otobiletexpress ve Uygulamaları üzerinden yapacağınız tüm işlemlerde müşteri hizmetleri ekibimiz 7/24 yanınızda. Bir tıkla Canlı Destek başlatabilir ve yardım alabilirsiniz."
    },
    {
      image: "/customer-service.png", description: "Güvenli Ödeme Tüm otobüs bilet alımlarınızı ister evinizden, ister ofisinizden ya da dilerseniz cep telefonunuzdan kolay, hızlı ve güvenilir bir şekilde gerçekleştirebilirsiniz."
    },
    { image: "/lock.png", description: "Otobiletexpress olarak, en seçkin otobüs firmalarını bir araya getiriyoruz. Tüm firmaların otobüs biletlerini Otobiletexpress üzerinde sorgulayabilir ve karşılaştırabilirsiniz. Böylece bütçenize uygun otobüs biletini rahatlıkla bulabilir ve online olarak satın alabilirsiniz." },
  ];

  return (
    <html lang="en">

      <body className={inter.className}>
        {children}
        <div className="page-container">
          <Header />
          <Image src="/MainImage.png" alt='MainPhoto' width={1270} height={430} />
          <div className="information" >Sizler için buradayız!
            Yolculuklarınızı konforlu ve bütçe dostu hale getirmek için çaba harcıyoruz. Geniş bilet seçenekleri sunuyoruz ve rahat otobüslerimizle seyahatinizi özel kılıyoruz. Güvende ve zamanında bir yolculuk için bizi tercih edin. Size uygun fiyatlı ve rahat bir seyahat deneyimi sunmak için buradayız. Şimdi biletinizi alın ve keyifli bir yolculuğa adım atın!</div>
          <Query />
          <Support
            supportItems={supportData} />
        </div>
      </body>
    </html>
  )
}
