import { VoyagesProps } from "./Voyages";
export const filteredVoyages: VoyagesProps[] = [
    {
        id: 1,
        acenty: "Kamil Koç",
        acentyImage: "",
        saat: "21.20",
        sure: "3 saat 23 dakika",
        kalkis: "Ankara",
        varis: "İstanbul",
        fiyat: "240 tl",
        tarih: "13.10.2023",
    },
    {
        id: 2,
        acenty: "Örnek Seyahat",
        acentyImage: "",
        saat: "19.45",
        sure: "2 saat 55 dakika",
        kalkis: "Hakkari",
        varis: "İstanbul",
        fiyat: "280 tl",
        tarih: "13.10.2023",
    },
    {
        id: 3,
        acenty: "Başka Bir Firma",
        acentyImage: "",
        saat: "18.30",
        sure: "4 saat 10 dakika",
        kalkis: "Hakkari",
        varis: "İstanbul",
        fiyat: "320 tl",
        tarih: "13.10.2023",
    },
    {
        id: 4,
        acenty: "Seyahat Şirketi",
        acentyImage: "",
        saat: "22.15",
        sure: "5 saat 45 dakika",
        kalkis: "Artvin",
        varis: "İstanbul",
        fiyat: "400 tl",
        tarih: "12.10.2023",
    },
    {
        id: 5,
        acenty: "Hızlı Seyahat",
        acentyImage: "",
        saat: "14.00",
        sure: "6 saat",
        kalkis: "İstanbul",
        varis: "Hakkari",
        fiyat: "350 tl",
        tarih: "12.10.2023",
    },
    {
        id: 6,
        acenty: "Express Seyahat",
        acentyImage: "",
        saat: "16.30",
        sure: "3 saat 40 dakika",
        kalkis: "Şırnak",
        varis: "Ankara",
        fiyat: "290 tl",
        tarih: "12.10.2023",
    },
    {
        id: 7,
        acenty: "Türk Rotaları",
        acentyImage: "",
        saat: "20.10",
        sure: "4 saat 15 dakika",
        kalkis: "Hakkari",
        varis: "Ankara",
        fiyat: "310 tl",
        tarih: "11.10.2023",
    },
    {
        id: 8,
        acenty: "Şehir Bağlantısı",
        acentyImage: "",
        saat: "23.30",
        sure: "5 saat 20 dakika",
        kalkis: "İstanbul",
        varis: "Artvin",
        fiyat: "380 tl",
        tarih: "12.10.2023",
    },
    {
        id: 9,
        acenty: "Dağ Rotası",
        acentyImage: "",
        saat: "12.15",
        sure: "7 saat 30 dakika",
        kalkis: "Artvin",
        varis: "Hakkari",
        fiyat: "420 tl",
        tarih: "11.10.2023",
    },
    {
        id: 10,
        acenty: "Express Hatlar",
        acentyImage: "",
        saat: "15.40",
        sure: "3 saat 10 dakika",
        kalkis: "İstanbul",
        varis: "Şırnak",
        fiyat: "300 tl",
        tarih: "08.10.2023",
    },
    {
        id: 11,
        acenty: "Türk Yolları",
        acentyImage: "",
        saat: "17.50",
        sure: "4 saat 55 dakika",
        kalkis: "Ankara",
        varis: "Artvin",
        fiyat: "350 tl",
        tarih: "10.10.2023",
    },
    {
        id: 12,
        acenty: "Yeşil Rotalar",
        acentyImage: "",
        saat: "13.20",
        sure: "6 saat 40 dakika",
        kalkis: "Hakkari",
        varis: "Artvin",
        fiyat: "400 tl",
        tarih: "10.10.2023",
    },
    {
        id: 13,
        acenty: "Sahil Seyahatleri",
        acentyImage: "",
        saat: "10.30",
        sure: "8 saat 15 dakika",
        kalkis: "Artvin",
        varis: "İstanbul",
        fiyat: "460 tl",
        tarih: "08.10.2023",
    },
    {
        id: 14,
        acenty: "Günbatımı Seyahatleri",
        acentyImage: "",
        saat: "19.00",
        sure: "5 saat 40 dakika",
        kalkis: "İstanbul",
        varis: "Ankara",
        fiyat: "320 tl",
        tarih: "08.10.2023",
    },
    {
        id: 15,
        acenty: "Altın Rotalar",
        acentyImage: "",
        saat: "14.45",
        sure: "6 saat 15 dakika",
        kalkis: "Şırnak",
        varis: "Hakkari",
        fiyat: "380 tl",
        tarih: "09.10.2023",
    },
    {
        id: 16,
        acenty: "Royal Seyahat",
        acentyImage: "",
        saat: "22.45",
        sure: "4 saat 50 dakika",
        kalkis: "Ankara",
        varis: "Hakkari",
        fiyat: "350 tl",
        tarih: "09.10.2023",
    },
    {
        id: 17,
        acenty: "Doğa Rotaları",
        acentyImage: "",
        saat: "16.20",
        sure: "5 saat 30 dakika",
        kalkis: "Artvin",
        varis: "Şırnak",
        fiyat: "330 tl",
        tarih: "13.10.2023",
    },
    {
        id: 18,
        acenty: "Dağ Rotaları",
        acentyImage: "",
        saat: "18.10",
        sure: "4 saat 45 dakika",
        kalkis: "İstanbul",
        varis: "Hakkari",
        fiyat: "360 tl",
        tarih: "13.10.2023",
    },
    {
        id: 19,
        acenty: "Günbatımı Seyahatleri",
        acentyImage: "",
        saat: "12.50",
        sure: "7 saat 10 dakika",
        kalkis: "Hakkari",
        varis: "Şırnak",
        fiyat: "390 tl",
        tarih: "14.10.2023",
    },
    {
        id: 20,
        acenty: "Mavi Rotalar",
        acentyImage: "",
        saat: "21.30",
        sure: "3 saat 50 dakika",
        kalkis: "Ankara",
        varis: "Artvin",
        fiyat: "340 tl",
        tarih: "14.10.2023",
    },
];
